// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_access_tokens.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAIAccessToken = `-- name: CreateAIAccessToken :exec
INSERT INTO ai_access_tokens (
    id,
    user_id,
    name,
    token_hash,
    token_prefix,
    created_at,
    last_used_at,
    revoked_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAIAccessTokenParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	TokenHash   string
	TokenPrefix string
	CreatedAt   pgtype.Timestamptz
	LastUsedAt  pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

func (q *Queries) CreateAIAccessToken(ctx context.Context, arg CreateAIAccessTokenParams) error {
	_, err := q.db.Exec(ctx, createAIAccessToken,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.CreatedAt,
		arg.LastUsedAt,
		arg.RevokedAt,
	)
	return err
}

const findActiveAIAccessTokenByHash = `-- name: FindActiveAIAccessTokenByHash :one
SELECT id, user_id, name, token_hash, token_prefix, created_at, last_used_at, revoked_at
FROM ai_access_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) FindActiveAIAccessTokenByHash(ctx context.Context, tokenHash string) (AiAccessToken, error) {
	row := q.db.QueryRow(ctx, findActiveAIAccessTokenByHash, tokenHash)
	var i AiAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAIAccessTokensByUserID = `-- name: ListAIAccessTokensByUserID :many
SELECT id, user_id, name, token_hash, token_prefix, created_at, last_used_at, revoked_at
FROM ai_access_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAIAccessTokensByUserID(ctx context.Context, userID uuid.UUID) ([]AiAccessToken, error) {
	rows, err := q.db.Query(ctx, listAIAccessTokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiAccessToken
	for rows.Next() {
		var i AiAccessToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAIAccessToken = `-- name: RevokeAIAccessToken :execrows
UPDATE ai_access_tokens
SET revoked_at = $3
WHERE user_id = $1
  AND id = $2
  AND revoked_at IS NULL
`

type RevokeAIAccessTokenParams struct {
	UserID    uuid.UUID
	ID        uuid.UUID
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeAIAccessToken(ctx context.Context, arg RevokeAIAccessTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAIAccessToken, arg.UserID, arg.ID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAIAccessTokenLastUsed = `-- name: TouchAIAccessTokenLastUsed :exec
UPDATE ai_access_tokens
SET last_used_at = $2
WHERE id = $1
  AND revoked_at IS NULL
`

type TouchAIAccessTokenLastUsedParams struct {
	ID         uuid.UUID
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) TouchAIAccessTokenLastUsed(ctx context.Context, arg TouchAIAccessTokenLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchAIAccessTokenLastUsed, arg.ID, arg.LastUsedAt)
	return err
}
