// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: company_aliases.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCompanyAlias = `-- name: CreateCompanyAlias :exec
INSERT INTO company_aliases (id, user_id, company_id, alias, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateCompanyAliasParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CompanyID uuid.UUID
	Alias     string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateCompanyAlias(ctx context.Context, arg CreateCompanyAliasParams) error {
	_, err := q.db.Exec(ctx, createCompanyAlias,
		arg.ID,
		arg.UserID,
		arg.CompanyID,
		arg.Alias,
		arg.CreatedAt,
	)
	return err
}

const deleteCompanyAlias = `-- name: DeleteCompanyAlias :execrows
DELETE FROM company_aliases
WHERE user_id = $1 AND id = $2
`

type DeleteCompanyAliasParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteCompanyAlias(ctx context.Context, arg DeleteCompanyAliasParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompanyAlias, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findCompanyAliasByID = `-- name: FindCompanyAliasByID :one
SELECT id, user_id, company_id, alias, created_at
FROM company_aliases
WHERE user_id = $1 AND id = $2
`

type FindCompanyAliasByIDParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) FindCompanyAliasByID(ctx context.Context, arg FindCompanyAliasByIDParams) (CompanyAlias, error) {
	row := q.db.QueryRow(ctx, findCompanyAliasByID, arg.UserID, arg.ID)
	var i CompanyAlias
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyID,
		&i.Alias,
		&i.CreatedAt,
	)
	return i, err
}

const listCompanyAliasesByCompanyID = `-- name: ListCompanyAliasesByCompanyID :many
SELECT id, user_id, company_id, alias, created_at
FROM company_aliases
WHERE user_id = $1 AND company_id = $2
ORDER BY created_at DESC
`

type ListCompanyAliasesByCompanyIDParams struct {
	UserID    uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) ListCompanyAliasesByCompanyID(ctx context.Context, arg ListCompanyAliasesByCompanyIDParams) ([]CompanyAlias, error) {
	rows, err := q.db.Query(ctx, listCompanyAliasesByCompanyID, arg.UserID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyAlias
	for rows.Next() {
		var i CompanyAlias
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyID,
			&i.Alias,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanyAliasesByUserID = `-- name: ListCompanyAliasesByUserID :many
SELECT id, user_id, company_id, alias, created_at
FROM company_aliases
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCompanyAliasesByUserID(ctx context.Context, userID uuid.UUID) ([]CompanyAlias, error) {
	rows, err := q.db.Query(ctx, listCompanyAliasesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyAlias
	for rows.Next() {
		var i CompanyAlias
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyID,
			&i.Alias,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
