// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: company.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCompany = `-- name: DeleteCompany :execrows
DELETE FROM companies
WHERE user_id = $1 AND id = $2
`

type DeleteCompanyParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteCompany(ctx context.Context, arg DeleteCompanyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompany, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findCompanyByID = `-- name: FindCompanyByID :one
SELECT id, user_id, name, memo, created_at, updated_at
FROM companies
WHERE user_id = $1 AND id = $2
`

type FindCompanyByIDParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) FindCompanyByID(ctx context.Context, arg FindCompanyByIDParams) (Company, error) {
	row := q.db.QueryRow(ctx, findCompanyByID, arg.UserID, arg.ID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Memo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompaniesByUserID = `-- name: ListCompaniesByUserID :many
SELECT id, user_id, name, memo, created_at, updated_at
FROM companies
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCompaniesByUserID(ctx context.Context, userID uuid.UUID) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompaniesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Memo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCompany = `-- name: UpsertCompany :exec
INSERT INTO companies (id, user_id, name, memo, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    name       = EXCLUDED.name,
    memo       = EXCLUDED.memo,
    updated_at = EXCLUDED.updated_at
`

type UpsertCompanyParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Memo      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertCompany(ctx context.Context, arg UpsertCompanyParams) error {
	_, err := q.db.Exec(ctx, upsertCompany,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Memo,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
