// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: entry.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEntry = `-- name: DeleteEntry :execrows
DELETE FROM entries
WHERE user_id = $1 AND id = $2
`

type DeleteEntryParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteEntry(ctx context.Context, arg DeleteEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEntry, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findEntryByID = `-- name: FindEntryByID :one
SELECT id, user_id, company_id, route, source, status, stage_kind, stage_label, memo, created_at, updated_at
FROM entries
WHERE user_id = $1 AND id = $2
`

type FindEntryByIDParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) FindEntryByID(ctx context.Context, arg FindEntryByIDParams) (Entry, error) {
	row := q.db.QueryRow(ctx, findEntryByID, arg.UserID, arg.ID)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyID,
		&i.Route,
		&i.Source,
		&i.Status,
		&i.StageKind,
		&i.StageLabel,
		&i.Memo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEntriesByUserID = `-- name: ListEntriesByUserID :many
SELECT id, user_id, company_id, route, source, status, stage_kind, stage_label, memo, created_at, updated_at
FROM entries
WHERE user_id = $1
  AND ($2::entry_status IS NULL OR status = $2)
  AND ($3::stage_kind IS NULL OR stage_kind = $3)
  AND ($4::text IS NULL OR source = $4)
ORDER BY updated_at DESC
`

type ListEntriesByUserIDParams struct {
	UserID    uuid.UUID
	Status    NullEntryStatus
	StageKind NullStageKind
	Source    pgtype.Text
}

func (q *Queries) ListEntriesByUserID(ctx context.Context, arg ListEntriesByUserIDParams) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntriesByUserID,
		arg.UserID,
		arg.Status,
		arg.StageKind,
		arg.Source,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyID,
			&i.Route,
			&i.Source,
			&i.Status,
			&i.StageKind,
			&i.StageLabel,
			&i.Memo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEntry = `-- name: UpsertEntry :exec
INSERT INTO entries (id, user_id, company_id, route, source, status, stage_kind, stage_label, memo, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO UPDATE SET
    route       = EXCLUDED.route,
    source      = EXCLUDED.source,
    status      = EXCLUDED.status,
    stage_kind  = EXCLUDED.stage_kind,
    stage_label = EXCLUDED.stage_label,
    memo        = EXCLUDED.memo,
    updated_at  = EXCLUDED.updated_at
`

type UpsertEntryParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	CompanyID  uuid.UUID
	Route      string
	Source     string
	Status     EntryStatus
	StageKind  StageKind
	StageLabel string
	Memo       string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) UpsertEntry(ctx context.Context, arg UpsertEntryParams) error {
	_, err := q.db.Exec(ctx, upsertEntry,
		arg.ID,
		arg.UserID,
		arg.CompanyID,
		arg.Route,
		arg.Source,
		arg.Status,
		arg.StageKind,
		arg.StageLabel,
		arg.Memo,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
