// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: es_memo.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createESMemo = `-- name: CreateESMemo :one
INSERT INTO es_memos (id, user_id, entry_id, category, title, content, source, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, entry_id, category, title, content, source, created_at, updated_at
`

type CreateESMemoParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	EntryID   pgtype.UUID
	Category  string
	Title     string
	Content   string
	Source    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateESMemo(ctx context.Context, arg CreateESMemoParams) (EsMemo, error) {
	row := q.db.QueryRow(ctx, createESMemo,
		arg.ID,
		arg.UserID,
		arg.EntryID,
		arg.Category,
		arg.Title,
		arg.Content,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i EsMemo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntryID,
		&i.Category,
		&i.Title,
		&i.Content,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listESMemosByUserID = `-- name: ListESMemosByUserID :many
SELECT id, user_id, entry_id, category, title, content, source, created_at, updated_at
FROM es_memos
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListESMemosByUserIDParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) ListESMemosByUserID(ctx context.Context, arg ListESMemosByUserIDParams) ([]EsMemo, error) {
	rows, err := q.db.Query(ctx, listESMemosByUserID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EsMemo
	for rows.Next() {
		var i EsMemo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntryID,
			&i.Category,
			&i.Title,
			&i.Content,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
