// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: external_identity.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findExternalIdentityByProviderAndSubject = `-- name: FindExternalIdentityByProviderAndSubject :one
SELECT id, user_id, provider, subject, created_at
FROM external_identities
WHERE provider = $1 AND subject = $2
`

type FindExternalIdentityByProviderAndSubjectParams struct {
	Provider AuthProvider
	Subject  string
}

func (q *Queries) FindExternalIdentityByProviderAndSubject(ctx context.Context, arg FindExternalIdentityByProviderAndSubjectParams) (ExternalIdentity, error) {
	row := q.db.QueryRow(ctx, findExternalIdentityByProviderAndSubject, arg.Provider, arg.Subject)
	var i ExternalIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.CreatedAt,
	)
	return i, err
}

const insertExternalIdentity = `-- name: InsertExternalIdentity :exec
INSERT INTO external_identities (id, user_id, provider, subject, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertExternalIdentityParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Provider  AuthProvider
	Subject   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertExternalIdentity(ctx context.Context, arg InsertExternalIdentityParams) error {
	_, err := q.db.Exec(ctx, insertExternalIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.CreatedAt,
	)
	return err
}
