// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: inbox_clips.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInboxClip = `-- name: CreateInboxClip :exec
INSERT INTO inbox_clips (id, user_id, url, title, source, guess, captured_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateInboxClipParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Url        string
	Title      string
	Source     string
	Guess      string
	CapturedAt pgtype.Timestamptz
}

func (q *Queries) CreateInboxClip(ctx context.Context, arg CreateInboxClipParams) error {
	_, err := q.db.Exec(ctx, createInboxClip,
		arg.ID,
		arg.UserID,
		arg.Url,
		arg.Title,
		arg.Source,
		arg.Guess,
		arg.CapturedAt,
	)
	return err
}

const deleteInboxClip = `-- name: DeleteInboxClip :execrows
DELETE FROM inbox_clips
WHERE user_id = $1 AND id = $2
`

type DeleteInboxClipParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteInboxClip(ctx context.Context, arg DeleteInboxClipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInboxClip, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findInboxClipByID = `-- name: FindInboxClipByID :one
SELECT id, user_id, url, title, source, guess, captured_at
FROM inbox_clips
WHERE user_id = $1 AND id = $2
`

type FindInboxClipByIDParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) FindInboxClipByID(ctx context.Context, arg FindInboxClipByIDParams) (InboxClip, error) {
	row := q.db.QueryRow(ctx, findInboxClipByID, arg.UserID, arg.ID)
	var i InboxClip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.Source,
		&i.Guess,
		&i.CapturedAt,
	)
	return i, err
}

const listInboxClipsByUserID = `-- name: ListInboxClipsByUserID :many
SELECT id, user_id, url, title, source, guess, captured_at
FROM inbox_clips
WHERE user_id = $1
ORDER BY captured_at DESC
`

func (q *Queries) ListInboxClipsByUserID(ctx context.Context, userID uuid.UUID) ([]InboxClip, error) {
	rows, err := q.db.Query(ctx, listInboxClipsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InboxClip
	for rows.Next() {
		var i InboxClip
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.Source,
			&i.Guess,
			&i.CapturedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
