// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const mCPGetEntryContext = `-- name: MCPGetEntryContext :one
SELECT
    e.id,
    e.company_id,
    c.name AS company_name,
    e.route,
    e.source,
    e.source_url,
    e.status,
    e.stage_kind,
    e.stage_label,
    e.memo,
    e.created_at,
    e.updated_at
FROM entries e
JOIN companies c ON c.id = e.company_id
WHERE e.user_id = $1 AND e.id = $2
`

type MCPGetEntryContextParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

type MCPGetEntryContextRow struct {
	ID          uuid.UUID
	CompanyID   uuid.UUID
	CompanyName string
	Route       string
	Source      string
	SourceUrl   string
	Status      EntryStatus
	StageKind   StageKind
	StageLabel  string
	Memo        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) MCPGetEntryContext(ctx context.Context, arg MCPGetEntryContextParams) (MCPGetEntryContextRow, error) {
	row := q.db.QueryRow(ctx, mCPGetEntryContext, arg.UserID, arg.ID)
	var i MCPGetEntryContextRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CompanyName,
		&i.Route,
		&i.Source,
		&i.SourceUrl,
		&i.Status,
		&i.StageKind,
		&i.StageLabel,
		&i.Memo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const mCPListEntries = `-- name: MCPListEntries :many
SELECT
    e.id,
    e.company_id,
    c.name AS company_name,
    e.route,
    e.source,
    e.source_url,
    e.status,
    e.stage_kind,
    e.stage_label,
    e.memo,
    e.created_at,
    e.updated_at
FROM entries e
JOIN companies c ON c.id = e.company_id
WHERE e.user_id = $1
ORDER BY e.updated_at DESC
`

type MCPListEntriesRow struct {
	ID          uuid.UUID
	CompanyID   uuid.UUID
	CompanyName string
	Route       string
	Source      string
	SourceUrl   string
	Status      EntryStatus
	StageKind   StageKind
	StageLabel  string
	Memo        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) MCPListEntries(ctx context.Context, userID uuid.UUID) ([]MCPListEntriesRow, error) {
	rows, err := q.db.Query(ctx, mCPListEntries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MCPListEntriesRow
	for rows.Next() {
		var i MCPListEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CompanyName,
			&i.Route,
			&i.Source,
			&i.SourceUrl,
			&i.Status,
			&i.StageKind,
			&i.StageLabel,
			&i.Memo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mCPListOpenTasks = `-- name: MCPListOpenTasks :many
SELECT
    t.id,
    t.entry_id,
    c.name AS company_name,
    t.title,
    t.task_type,
    t.due_date,
    t.status,
    t.notify,
    t.memo,
    t.created_at,
    t.updated_at
FROM tasks t
JOIN entries e ON e.id = t.entry_id
JOIN companies c ON c.id = e.company_id
WHERE e.user_id = $1 AND t.status = 'todo'
ORDER BY t.due_date ASC NULLS LAST, t.created_at ASC
`

type MCPListOpenTasksRow struct {
	ID          uuid.UUID
	EntryID     uuid.UUID
	CompanyName string
	Title       string
	TaskType    TaskType
	DueDate     pgtype.Timestamptz
	Status      TaskStatus
	Notify      bool
	Memo        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) MCPListOpenTasks(ctx context.Context, userID uuid.UUID) ([]MCPListOpenTasksRow, error) {
	rows, err := q.db.Query(ctx, mCPListOpenTasks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MCPListOpenTasksRow
	for rows.Next() {
		var i MCPListOpenTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.CompanyName,
			&i.Title,
			&i.TaskType,
			&i.DueDate,
			&i.Status,
			&i.Notify,
			&i.Memo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
