// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthProvider string

const (
	AuthProviderGoogle AuthProvider = "google"
)

func (e *AuthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProvider(s)
	case string:
		*e = AuthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProvider: %T", src)
	}
	return nil
}

type NullAuthProvider struct {
	AuthProvider AuthProvider
	Valid        bool // Valid is true if AuthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProvider), nil
}

type EntryStatus string

const (
	EntryStatusInProgress EntryStatus = "in_progress"
	EntryStatusOffered    EntryStatus = "offered"
	EntryStatusAccepted   EntryStatus = "accepted"
	EntryStatusRejected   EntryStatus = "rejected"
	EntryStatusWithdrawn  EntryStatus = "withdrawn"
)

func (e *EntryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntryStatus(s)
	case string:
		*e = EntryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EntryStatus: %T", src)
	}
	return nil
}

type NullEntryStatus struct {
	EntryStatus EntryStatus
	Valid       bool // Valid is true if EntryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EntryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntryStatus), nil
}

type StageKind string

const (
	StageKindApplication StageKind = "application"
	StageKindDocument    StageKind = "document"
	StageKindTest        StageKind = "test"
	StageKindInterview   StageKind = "interview"
	StageKindGroup       StageKind = "group"
	StageKindOffer       StageKind = "offer"
	StageKindOther       StageKind = "other"
)

func (e *StageKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StageKind(s)
	case string:
		*e = StageKind(s)
	default:
		return fmt.Errorf("unsupported scan type for StageKind: %T", src)
	}
	return nil
}

type NullStageKind struct {
	StageKind StageKind
	Valid     bool // Valid is true if StageKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStageKind) Scan(value interface{}) error {
	if value == nil {
		ns.StageKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StageKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStageKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StageKind), nil
}

type TaskStatus string

const (
	TaskStatusTodo TaskStatus = "todo"
	TaskStatusDone TaskStatus = "done"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus
	Valid      bool // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type TaskType string

const (
	TaskTypeDeadline TaskType = "deadline"
	TaskTypeSchedule TaskType = "schedule"
)

func (e *TaskType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskType(s)
	case string:
		*e = TaskType(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskType: %T", src)
	}
	return nil
}

type NullTaskType struct {
	TaskType TaskType
	Valid    bool // Valid is true if TaskType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskType) Scan(value interface{}) error {
	if value == nil {
		ns.TaskType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskType), nil
}

type Company struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Memo      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type CompanyAlias struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CompanyID uuid.UUID
	Alias     string
	CreatedAt pgtype.Timestamptz
}

type Entry struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	CompanyID  uuid.UUID
	Route      string
	Source     string
	Status     EntryStatus
	StageKind  StageKind
	StageLabel string
	Memo       string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ExternalIdentity struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Provider  AuthProvider
	Subject   string
	CreatedAt pgtype.Timestamptz
}

type PasswordCredential struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type StageHistory struct {
	ID         uuid.UUID
	EntryID    uuid.UUID
	StageKind  StageKind
	StageLabel string
	Note       string
	CreatedAt  pgtype.Timestamptz
}

type Task struct {
	ID        uuid.UUID
	EntryID   uuid.UUID
	Title     string
	TaskType  TaskType
	DueDate   pgtype.Timestamptz
	Status    TaskStatus
	Notify    bool
	Memo      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID        uuid.UUID
	Email     string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
