// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAIAccessToken(ctx context.Context, arg CreateAIAccessTokenParams) error
	CreateCompanyAlias(ctx context.Context, arg CreateCompanyAliasParams) error
	CreateESMemo(ctx context.Context, arg CreateESMemoParams) (EsMemo, error)
	CreateInboxClip(ctx context.Context, arg CreateInboxClipParams) error
	CreateStageHistory(ctx context.Context, arg CreateStageHistoryParams) error
	DeleteCompany(ctx context.Context, arg DeleteCompanyParams) (int64, error)
	DeleteCompanyAlias(ctx context.Context, arg DeleteCompanyAliasParams) (int64, error)
	DeleteEntry(ctx context.Context, arg DeleteEntryParams) (int64, error)
	DeleteInboxClip(ctx context.Context, arg DeleteInboxClipParams) (int64, error)
	DeleteTask(ctx context.Context, arg DeleteTaskParams) (int64, error)
	DeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	FindActiveAIAccessTokenByHash(ctx context.Context, tokenHash string) (AiAccessToken, error)
	FindCompanyAliasByID(ctx context.Context, arg FindCompanyAliasByIDParams) (CompanyAlias, error)
	FindCompanyByID(ctx context.Context, arg FindCompanyByIDParams) (Company, error)
	FindEntryByID(ctx context.Context, arg FindEntryByIDParams) (Entry, error)
	FindExternalIdentityByProviderAndSubject(ctx context.Context, arg FindExternalIdentityByProviderAndSubjectParams) (ExternalIdentity, error)
	FindInboxClipByID(ctx context.Context, arg FindInboxClipByIDParams) (InboxClip, error)
	FindInboxClipByUserIDAndURL(ctx context.Context, arg FindInboxClipByUserIDAndURLParams) (InboxClip, error)
	FindTaskByID(ctx context.Context, arg FindTaskByIDParams) (Task, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByID(ctx context.Context, id uuid.UUID) (User, error)
	InsertExternalIdentity(ctx context.Context, arg InsertExternalIdentityParams) error
	ListAIAccessTokensByUserID(ctx context.Context, userID uuid.UUID) ([]AiAccessToken, error)
	ListCompaniesByUserID(ctx context.Context, userID uuid.UUID) ([]Company, error)
	ListCompanyAliasesByCompanyID(ctx context.Context, arg ListCompanyAliasesByCompanyIDParams) ([]CompanyAlias, error)
	ListCompanyAliasesByUserID(ctx context.Context, userID uuid.UUID) ([]CompanyAlias, error)
	ListESMemosByUserID(ctx context.Context, arg ListESMemosByUserIDParams) ([]EsMemo, error)
	ListEntriesByUserID(ctx context.Context, arg ListEntriesByUserIDParams) ([]Entry, error)
	ListInboxClipsByUserID(ctx context.Context, userID uuid.UUID) ([]InboxClip, error)
	ListStageHistoriesByEntryID(ctx context.Context, arg ListStageHistoriesByEntryIDParams) ([]StageHistory, error)
	ListTasksByEntryID(ctx context.Context, arg ListTasksByEntryIDParams) ([]Task, error)
	ListTasksByUserID(ctx context.Context, userID uuid.UUID) ([]Task, error)
	ListTasksByUserIDWithDueBefore(ctx context.Context, arg ListTasksByUserIDWithDueBeforeParams) ([]Task, error)
	MCPGetEntryContext(ctx context.Context, arg MCPGetEntryContextParams) (MCPGetEntryContextRow, error)
	MCPListEntries(ctx context.Context, userID uuid.UUID) ([]MCPListEntriesRow, error)
	MCPListOpenTasks(ctx context.Context, userID uuid.UUID) ([]MCPListOpenTasksRow, error)
	RevokeAIAccessToken(ctx context.Context, arg RevokeAIAccessTokenParams) (int64, error)
	TouchAIAccessTokenLastUsed(ctx context.Context, arg TouchAIAccessTokenLastUsedParams) error
	UpsertCompany(ctx context.Context, arg UpsertCompanyParams) error
	UpsertEntry(ctx context.Context, arg UpsertEntryParams) error
	UpsertTask(ctx context.Context, arg UpsertTaskParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
}

var _ Querier = (*Queries)(nil)
