// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: selection_flow.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSelectionStage = `-- name: CreateSelectionStage :exec
INSERT INTO selection_stages (id, flow_id, position, stage_kind, stage_label, evidence_text, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateSelectionStageParams struct {
	ID           uuid.UUID
	FlowID       uuid.UUID
	Position     int32
	StageKind    StageKind
	StageLabel   string
	EvidenceText string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateSelectionStage(ctx context.Context, arg CreateSelectionStageParams) error {
	_, err := q.db.Exec(ctx, createSelectionStage,
		arg.ID,
		arg.FlowID,
		arg.Position,
		arg.StageKind,
		arg.StageLabel,
		arg.EvidenceText,
		arg.CreatedAt,
	)
	return err
}

const deleteSelectionStagesByFlowID = `-- name: DeleteSelectionStagesByFlowID :exec
DELETE FROM selection_stages
WHERE flow_id = $1
`

func (q *Queries) DeleteSelectionStagesByFlowID(ctx context.Context, flowID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSelectionStagesByFlowID, flowID)
	return err
}

const findSelectionFlowByEntryID = `-- name: FindSelectionFlowByEntryID :one
SELECT sf.id, sf.entry_id, sf.source, sf.current_stage_position, sf.confidence, sf.inbox_clip_id, sf.created_at, sf.updated_at
FROM selection_flows sf
JOIN entries e ON e.id = sf.entry_id
WHERE e.user_id = $1 AND sf.entry_id = $2
`

type FindSelectionFlowByEntryIDParams struct {
	UserID  uuid.UUID
	EntryID uuid.UUID
}

func (q *Queries) FindSelectionFlowByEntryID(ctx context.Context, arg FindSelectionFlowByEntryIDParams) (SelectionFlow, error) {
	row := q.db.QueryRow(ctx, findSelectionFlowByEntryID, arg.UserID, arg.EntryID)
	var i SelectionFlow
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Source,
		&i.CurrentStagePosition,
		&i.Confidence,
		&i.InboxClipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSelectionStagesByFlowID = `-- name: ListSelectionStagesByFlowID :many
SELECT id, flow_id, position, stage_kind, stage_label, evidence_text, created_at
FROM selection_stages
WHERE flow_id = $1
ORDER BY position ASC
`

func (q *Queries) ListSelectionStagesByFlowID(ctx context.Context, flowID uuid.UUID) ([]SelectionStage, error) {
	rows, err := q.db.Query(ctx, listSelectionStagesByFlowID, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectionStage
	for rows.Next() {
		var i SelectionStage
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.Position,
			&i.StageKind,
			&i.StageLabel,
			&i.EvidenceText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSelectionFlow = `-- name: UpsertSelectionFlow :one
INSERT INTO selection_flows (
    id,
    entry_id,
    source,
    current_stage_position,
    confidence,
    inbox_clip_id,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (entry_id) DO UPDATE SET
    source = EXCLUDED.source,
    current_stage_position = EXCLUDED.current_stage_position,
    confidence = EXCLUDED.confidence,
    inbox_clip_id = EXCLUDED.inbox_clip_id,
    updated_at = EXCLUDED.updated_at
RETURNING id, entry_id, source, current_stage_position, confidence, inbox_clip_id, created_at, updated_at
`

type UpsertSelectionFlowParams struct {
	ID                   uuid.UUID
	EntryID              uuid.UUID
	Source               string
	CurrentStagePosition int32
	Confidence           pgtype.Int4
	InboxClipID          pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) UpsertSelectionFlow(ctx context.Context, arg UpsertSelectionFlowParams) (SelectionFlow, error) {
	row := q.db.QueryRow(ctx, upsertSelectionFlow,
		arg.ID,
		arg.EntryID,
		arg.Source,
		arg.CurrentStagePosition,
		arg.Confidence,
		arg.InboxClipID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SelectionFlow
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Source,
		&i.CurrentStagePosition,
		&i.Confidence,
		&i.InboxClipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
