// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stage_history.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStageHistory = `-- name: CreateStageHistory :exec
INSERT INTO stage_histories (id, entry_id, stage_kind, stage_label, note, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateStageHistoryParams struct {
	ID         uuid.UUID
	EntryID    uuid.UUID
	StageKind  StageKind
	StageLabel string
	Note       string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateStageHistory(ctx context.Context, arg CreateStageHistoryParams) error {
	_, err := q.db.Exec(ctx, createStageHistory,
		arg.ID,
		arg.EntryID,
		arg.StageKind,
		arg.StageLabel,
		arg.Note,
		arg.CreatedAt,
	)
	return err
}

const listStageHistoriesByEntryID = `-- name: ListStageHistoriesByEntryID :many
SELECT sh.id, sh.entry_id, sh.stage_kind, sh.stage_label, sh.note, sh.created_at
FROM stage_histories sh
JOIN entries e ON e.id = sh.entry_id
WHERE e.user_id = $1 AND sh.entry_id = $2
ORDER BY sh.created_at
`

type ListStageHistoriesByEntryIDParams struct {
	UserID  uuid.UUID
	EntryID uuid.UUID
}

func (q *Queries) ListStageHistoriesByEntryID(ctx context.Context, arg ListStageHistoriesByEntryIDParams) ([]StageHistory, error) {
	rows, err := q.db.Query(ctx, listStageHistoriesByEntryID, arg.UserID, arg.EntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StageHistory
	for rows.Next() {
		var i StageHistory
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.StageKind,
			&i.StageLabel,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
