// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: task.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTask = `-- name: DeleteTask :execrows
DELETE FROM tasks
USING entries e
WHERE tasks.entry_id = e.id AND e.user_id = $1 AND tasks.id = $2
`

type DeleteTaskParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTask, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findTaskByID = `-- name: FindTaskByID :one
SELECT t.id, t.entry_id, t.title, t.task_type, t.due_date, t.status, t.notify, t.memo, t.created_at, t.updated_at
FROM tasks t
JOIN entries e ON t.entry_id = e.id
WHERE e.user_id = $1 AND t.id = $2
`

type FindTaskByIDParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) FindTaskByID(ctx context.Context, arg FindTaskByIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, findTaskByID, arg.UserID, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Title,
		&i.TaskType,
		&i.DueDate,
		&i.Status,
		&i.Notify,
		&i.Memo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasksByEntryID = `-- name: ListTasksByEntryID :many
SELECT t.id, t.entry_id, t.title, t.task_type, t.due_date, t.status, t.notify, t.memo, t.created_at, t.updated_at
FROM tasks t
JOIN entries e ON t.entry_id = e.id
WHERE e.user_id = $1 AND t.entry_id = $2
ORDER BY t.created_at
`

type ListTasksByEntryIDParams struct {
	UserID  uuid.UUID
	EntryID uuid.UUID
}

func (q *Queries) ListTasksByEntryID(ctx context.Context, arg ListTasksByEntryIDParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByEntryID, arg.UserID, arg.EntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.Title,
			&i.TaskType,
			&i.DueDate,
			&i.Status,
			&i.Notify,
			&i.Memo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByUserIDWithDueBefore = `-- name: ListTasksByUserIDWithDueBefore :many
SELECT t.id, t.entry_id, t.title, t.task_type, t.due_date, t.status, t.notify, t.memo, t.created_at, t.updated_at
FROM tasks t
JOIN entries e ON t.entry_id = e.id
WHERE e.user_id = $1 AND t.status = 'todo' AND t.due_date < $2
ORDER BY t.due_date
`

type ListTasksByUserIDWithDueBeforeParams struct {
	UserID  uuid.UUID
	DueDate pgtype.Timestamptz
}

func (q *Queries) ListTasksByUserIDWithDueBefore(ctx context.Context, arg ListTasksByUserIDWithDueBeforeParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByUserIDWithDueBefore, arg.UserID, arg.DueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.Title,
			&i.TaskType,
			&i.DueDate,
			&i.Status,
			&i.Notify,
			&i.Memo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTask = `-- name: UpsertTask :exec
INSERT INTO tasks (id, entry_id, title, task_type, due_date, status, notify, memo, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (id) DO UPDATE SET
    title      = EXCLUDED.title,
    task_type  = EXCLUDED.task_type,
    due_date   = EXCLUDED.due_date,
    status     = EXCLUDED.status,
    notify     = EXCLUDED.notify,
    memo       = EXCLUDED.memo,
    updated_at = EXCLUDED.updated_at
`

type UpsertTaskParams struct {
	ID        uuid.UUID
	EntryID   uuid.UUID
	Title     string
	TaskType  TaskType
	DueDate   pgtype.Timestamptz
	Status    TaskStatus
	Notify    bool
	Memo      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertTask(ctx context.Context, arg UpsertTaskParams) error {
	_, err := q.db.Exec(ctx, upsertTask,
		arg.ID,
		arg.EntryID,
		arg.Title,
		arg.TaskType,
		arg.DueDate,
		arg.Status,
		arg.Notify,
		arg.Memo,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
